config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

# debug 가 true 라는것은 development 환경일때를 의미
# 즉 개발환경에서는 사진들을 저장한 폴더에 접근할 수 있게 해준다는 것임
# 실제 프로덕트 환경 즉, 서버 환경에서는 절때 서버에 존재하는 폴더에 접근하게 해주면 안됨

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete-verification"
    ),
]

templates/partials/footer.html
<footer>
    &copy; 쵸니BnB
</footer>

templates/partials/header.html
<a href="{% url "core:home" %}">쵸니BnB</a>
<ul>
    {% if  user.is_authenticated %}
        <li><a href="{% url "users:logout" %}">LogOut</a></li>
    {% else %}
        <li><a href="{% url "users:login" %}">Login</a></li>
        <li><a href="{% url "users:signup" %}">SignUp</a></li>
    {% endif %}

</ul>

templates/partials/social_login.html
<div>
    <a href="{% url 'users:github-login' %}">
        Continue with Github
    </a>
    <a href="{% url 'users:kakao-login' %}">
        Continue with Kakao
    </a>
</div>