config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

# debug 가 true 라는것은 development 환경일때를 의미
# 즉 개발환경에서는 사진들을 저장한 폴더에 접근할 수 있게 해준다는 것임
# 실제 프로덕트 환경 즉, 서버 환경에서는 절때 서버에 존재하는 폴더에 접근하게 해주면 안됨

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("search/", views.search, name="search"),
]

rooms/models.py
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField
from core import models as core_models
from users import models as user_models


class AbstractItem(core_models.TimeStampedModel):

    """ Abstract Item """

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstractItem):

    """ RoomType Model Definition"""

    class Meta:
        verbose_name_plural = "Room Types"


class Amenity(AbstractItem):

    """ Amenity Model Definition"""

    class Meta:
        verbose_name_plural = "Amenities"


class Facility(AbstractItem):

    """ Facility Model Definition"""

    class Meta:
        verbose_name_plural = "Facilities"


class HouseRule(AbstractItem):

    """ HouseRule Model Definition """

    class Meta:
        verbose_name_plural = "House Rules"


class Photo(core_models.TimeStampedModel):

    """ Photo Model Definition """

    caption = models.CharField(max_length=200)
    file = models.ImageField(upload_to="room_photos")
    room = models.ForeignKey("Room", related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption


class Room(core_models.TimeStampedModel):

    """ Room Model """

    name = models.CharField(max_length=140)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=80)
    price = models.IntegerField()
    address = models.CharField(max_length=140)
    guests = models.IntegerField()
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)
    host = models.ForeignKey(
        user_models.User, related_name="rooms", on_delete=models.CASCADE
    )
    room_type = models.ForeignKey(
        RoomType, related_name="rooms", on_delete=models.SET_NULL, null=True
    )
    amenities = models.ManyToManyField(Amenity, related_name="rooms", blank=True)
    facilities = models.ManyToManyField(Facility, related_name="rooms", blank=True)
    house_rules = models.ManyToManyField(HouseRule, related_name="rooms", blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.city = str.capitalize(self.city)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("rooms:detail", kwargs={"pk": self.pk})

    def total_rating(self):
        all_reviews = self.reviews.all()
        all_ratings = 0
        if len(all_reviews) > 0:
            for review in all_reviews:
                all_ratings += review.rating_average()
            return all_ratings / len(all_reviews)
        return 0

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from . import models


class SearchForm(forms.Form):

    city = forms.CharField(initial="Anywhere", empty_value="Anywhere", required=False)
    country = CountryField(default="KR").formfield(required=False)
    room_type = forms.ModelChoiceField(
        required=False, empty_label="Any Kind", queryset=models.RoomType.objects.all()
    )
    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    instant_book = forms.BooleanField(required=False)
    superhost = forms.BooleanField(required=False)
    amenities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    facilities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

rooms/views.py
from django.views.generic import ListView, DetailView
from django.utils import timezone
from django.shortcuts import render
from django.core.paginator import Paginator
from . import forms
from . import models


class HomeView(ListView):

    """ HomeView Class Definition """

    model = models.Room
    paginate_by = 10
    paginate_orphans = 3
    context_object_name = "rooms"

    # context를 custom 할 수 있다
    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        now = timezone.now()

        context["now"] = now

        return context


class RoomDetail(DetailView):

    model = models.Room

    # 이거 안해도 DetailView 는 기본으로 argument를 pk로 받음
    pk_url_kwarg = "pk"


def search(request):

    city = request.GET.get("city")

    country = request.GET.get("country")

    if city is not None and country is None:

        form = forms.SearchForm(request.GET)

        rooms = models.Room.objects.filter(city=city)

        return render(request, "rooms/search.html", {"form": form, "rooms": rooms})

    if country and city:

        form = forms.SearchForm(request.GET)

        if form.is_valid():

            city = form.cleaned_data.get("city")
            country = form.cleaned_data.get("country")
            room_type = form.cleaned_data.get("room_type")
            price = form.cleaned_data.get("price")
            guests = form.cleaned_data.get("guests")
            bedrooms = form.cleaned_data.get("bedrooms")
            beds = form.cleaned_data.get("beds")
            baths = form.cleaned_data.get("baths")
            instant_book = form.cleaned_data.get("instant_book")
            superhost = form.cleaned_data.get("superhost")
            amenities = form.cleaned_data.get("amenities")
            facilities = form.cleaned_data.get("facilities")

            filter_args = {}

            if city != "Anywhere":
                filter_args["city__startswith"] = city

            filter_args["country"] = country

            if room_type is not None:
                filter_args["room_type"] = room_type

            if price is not None:
                filter_args["price__lte"] = price

            if guests is not None:
                filter_args["guests__gte"] = guests

            if bedrooms is not None:
                filter_args["bedrooms__gte"] = bedrooms

            if beds is not None:
                filter_args["ged__gte"] = beds

            if baths is not None:
                filter_args["baths__gte"] = baths

            if instant_book is True:
                filter_args["instant_book"] = True

            if superhost is True:
                filter_args["host__superhost"] = True

            if len(amenities) > 0:
                filter_args["amenities__in"] = list(amenities)

            if len(facilities) > 0:
                filter_args["facilities__in"] = list(facilities)

            qs = (
                models.Room.objects.filter(**filter_args)
                .order_by("-created")
                .distinct()
            )

            paginator = Paginator(qs, 10, orphans=5)

            page = request.GET.get("page", 1)

            rooms = paginator.get_page(page)

            return render(request, "rooms/search.html", {"form": form, "rooms": rooms})
    else:

        form = forms.SearchForm()

        return render(request, "rooms/search.html", {"form": form})

templates/rooms/detail.html
{% extends "base.html" %}



{% block page_name %}
  Home 
{% endblock page_name %}



{% block content %}

<div>
  <h1>{{room.name}}</h1>
  <h3>{{room.description}}</h3>
</div>

<div>
  <h3>
  {{room.host.username}} 
  {% if room.host.superhost %}
    ✅ SH ✅
  {% endif %}
  </h3>
</div>

<div>
  <h4>Amenities</h4>
  {% for a in room.amenities.all %}
    <ul>
      <li>{{a}}</li>
    </ul>
  {% endfor %}

    <h4>Facilities</h4>
  {% for f in room.facilities.all %}
    <ul>
      <li>{{f}}</li>
    </ul>
  {% endfor %}

    <h4>House Rules</h4>
  {% for h in room.house_rules.all %}
    <ul>
      <li>{{h}}</li>
    </ul>
  {% endfor %}
</div>

{% endblock content %}

templates/rooms/room_detail.html
{% extends "base.html" %}



{% block page_title %}
  {{room.name}} 
{% endblock page_title %}



{% block content %}

<div>
  <h1>{{room.name}}</h1>
  <h3>{{room.description}}</h3>
</div>

<div>
  <h3>
  {{room.host.username}} 
  {% if room.host.superhost %}
    ✅ SH ✅
  {% endif %}
  </h3>
</div>

<div>
  <h4>Amenities</h4>
  {% for a in room.amenities.all %}
    <ul>
      <li>{{a}}</li>
    </ul>
  {% endfor %}

    <h4>Facilities</h4>
  {% for f in room.facilities.all %}
    <ul>
      <li>{{f}}</li>
    </ul>
  {% endfor %}

    <h4>House Rules</h4>
  {% for h in room.house_rules.all %}
    <ul>
      <li>{{h}}</li>
    </ul>
  {% endfor %}
</div>

{% endblock content %}

templates/rooms/room_list.html
{% extends "base.html" %}



{% block page_title %}
  Home 
{% endblock page_title %}



{% block content %}

<h4>{{now}}</h4>

{% for room in rooms %}

{% comment %} 
namespace와 name을 이용해서 url을 편하게 작성할 수 있음 뒤에는 argument를 작성한 것  
{% endcomment %}
<h2> <a href="{% url "rooms:detail" room.pk %}">💒 {{room}}  💰 ${{room.price}}</a></h2>
{% endfor %}

<h5>
{% if page_obj.has_previous %}
  <a href="?page={{page_obj.previous_page_number}}">Prev</a>
{% endif %}

Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}

{% if page_obj.has_next %}
  <a href="?page={{page_obj.next_page_number}}">Next</a>
{% endif %}
</h5>

{% endblock content %}

templates/rooms/search.html
{% extends "base.html" %}

{% block page_title %}
    Search 
{% endblock page_title %}

{% comment %}
base.html 에 search-bar를 넣어놨으니 모든 템플릿에 그 block 이 보일것임 (base.html을 extends를 했다면)
근데 우리는 이 search 템플릿에서 그것을 보여주고싶지않음 밑에 content block에 이미 있기 때문에 
그래서 같은 이름의 block을 만들어서 아무것도 안넣으면 보이지 않게 되는 것 
{% endcomment %}
{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <h2>Search !</h2>

    <form method="get" action="{% url "rooms:search" %}">
        {{form.as_p}}
        <button>Search</button>
    </form>

    <div>
    <h2>Result for Search</h2>
        {% for room in rooms %}
            <h4>{{room.name}}</h4>
        {% endfor %}
    </div>

{% endblock content %}